#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd) 
PROJECT_ROOT="$SCRIPT_DIR/../.."

BINARIES=(babel eslint istanbul mocha nodemon)

for binary in ${BINARIES[@]}; do
    if [ ! -L "$PROJECT_ROOT/$binary" ]; then
        $(cd "$PROJECT_ROOT" && ln -s "node_modules/.bin/$binary")
    fi
done
